"""Tool that generates a structured markdown explanation from query results."""

from langchain_core.tools import tool

from backend.utils.llm import get_llm

EXPLANATION_PROMPT = """\
You are a data analyst explaining SQL query results to a user.

Original user question: {user_question}

SQL query results (JSON):
{query_results}

A chart was {chart_status} generated.

Write a concise markdown explanation that:
1. Answers the user's question directly in the first sentence.
2. Highlights the key numbers and insights from the data.
3. Mentions trends, outliers, or noteworthy patterns if present.
4. If a chart was generated, add a brief caption describing what it shows.

Keep the explanation focused and data-driven. Do not make up numbers
that are not in the query results. Use markdown formatting (bold,
bullet points) where it improves readability.
"""


@tool
def generate_explanation(
    user_question: str, query_results: str, has_chart: bool
) -> str:
    """Generate a structured markdown explanation from SQL query results.

    Call this tool LAST, after you have run the SQL query and (optionally)
    generated a chart.  It produces the final answer that will be shown
    to the user.

    Args:
        user_question: The user's original question verbatim.
        query_results: The JSON results from run_sql_query.
        has_chart: True if a chart was generated by generate_chart.

    Returns:
        A markdown-formatted explanation string.
    """
    chart_status = "also" if has_chart else "not"
    prompt = EXPLANATION_PROMPT.format(
        user_question=user_question,
        query_results=query_results,
        chart_status=chart_status,
    )

    llm = get_llm("cloud")
    response = llm.invoke(prompt)
    return response.content
