"""State schema and structured-output models for the SQL Agent StateGraph."""

from enum import Enum
from typing import Annotated, Any, TypedDict

from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class UserIntent(str, Enum):
    QUESTION = "question"
    EXPLAIN = "explain"
    HOWTO = "how-to"
    SUMMARIZE = "summarize"
    TRANSLATE = "translate"
    COMPARE = "compare"
    LIST = "list"
    GENERATE = "generate"
    CODE = "code"
    OTHER = "other"


# Intents that should be routed through the SQL pipeline.
_DATA_QUESTION_INTENTS = frozenset(
    {UserIntent.QUESTION, UserIntent.COMPARE, UserIntent.LIST, UserIntent.GENERATE}
)

# Keywords that signal the user explicitly wants a chart.
_CHART_KEYWORDS = frozenset(
    {
        "chart", "plot", "graph", "visualize", "visualization",
        "trend", "bar chart", "line chart", "pie chart",
        "histogram", "bar", "line", "pie",
    }
)


# ---------------------------------------------------------------------------
# Pydantic models for structured LLM output
# ---------------------------------------------------------------------------


class ContextBlock(BaseModel):
    """A verbatim block (code, text, table, etc.) extracted from the user prompt."""

    block_type: str = Field(
        description="The type of block: 'code', 'text', 'table', 'quote', etc.",
    )
    language: str | None = Field(
        default=None,
        description="Programming language if block_type is 'code'; otherwise None.",
    )
    content: str = Field(
        description="Verbatim content, preserving whitespace and newlines.",
    )


class ClarifyingUserIntent(BaseModel):
    """Structured analysis of a user prompt, produced by the clarify-intent node."""

    type_of_request: UserIntent = Field(
        description="The fine-grained type of user request.",
    )
    core_intent: str = Field(
        description="The user's core intent in imperative form.",
    )
    keywords: list[str] = Field(
        default_factory=list,
        description="High-impact terms directly related to the core intent (max 15).",
    )
    style: str = Field(
        default="prose",
        description="How the output should be presented (prose, bullet points, etc.).",
    )
    output_format: str = Field(
        default="markdown",
        description="The output format (markdown, json, html, python code, etc.).",
    )
    tone: str = Field(
        default="neutral",
        description="Desired tone (formal, casual, humorous, technical, simple, ELI5, etc.).",
    )
    additional_instructions: str = Field(
        default="",
        description="Any remaining constraints, audience, or instructions verbatim.",
    )
    context_blocks: list[ContextBlock] = Field(
        default_factory=list,
        description="Verbatim code blocks, quoted passages, or data snippets.",
    )


class SQLQuery(BaseModel):
    """A SQL query produced by the generate-sql node."""

    query: str = Field(description="The SELECT SQL query to execute.")
    explanation: str = Field(
        description="Brief explanation of what this query does and why."
    )


class KeyFinding(BaseModel):
    """A single key insight extracted from query results."""

    insight: str = Field(description="The data insight or finding.")
    value: str | None = Field(
        default=None, description="The numeric or categorical value, if applicable."
    )


class Report(BaseModel):
    """Final report generated by the generate-report node for leadership."""

    executive_summary: str = Field(
        description="One-paragraph executive summary answering the user's question."
    )
    key_findings: list[KeyFinding] = Field(
        description="Bullet-point key findings from the data (3-7 items)."
    )
    recommendations: list[str] = Field(
        description="Actionable recommendations based on the findings (2-5 items).",
        default_factory=list,
    )
    narrative: str = Field(
        description="Full markdown narrative for the leadership team with all details."
    )


# ---------------------------------------------------------------------------
# LangGraph agent state (TypedDict)
# ---------------------------------------------------------------------------


class AgentState(TypedDict, total=False):
    """Shared state that flows through the SQL Agent StateGraph nodes.

    Each node writes to its own field(s); no two nodes write to the same
    field, so the default overwrite reducer is sufficient for all fields.
    ``total=False`` means every key is optional — nodes only return the
    fields they update.
    """

    # ---- Input ---------------------------------------------------------------
    user_query: str
    llm_type: str

    # ---- Message history (for LangGraph compatibility) -----------------------
    messages: Annotated[list[BaseMessage], add_messages]

    # ---- Clarification -------------------------------------------------------
    intent: ClarifyingUserIntent

    # ---- Schema info ---------------------------------------------------------
    schema_info: str

    # ---- SQL generation ------------------------------------------------------
    sql_query: SQLQuery

    # ---- SQL validation -------------------------------------------------------
    sql_validation_error: str  # Error fed back to generate_sql on retry
    sql_validation_attempts: int  # Retry counter (starts at 0)

    # ---- SQL execution -------------------------------------------------------
    columns: list[str]
    rows: list[dict[str, Any]]
    execution_error: str

    # ---- Chart ---------------------------------------------------------------
    chart_image: str   # base64 PNG data URI
    chart_error: str

    # ---- Report --------------------------------------------------------------
    report: Report

    # ---- Final output --------------------------------------------------------
    final_response: str  # For chat (non-data) responses.
    final_error: str     # Catch-all error surfaced to the caller.


def user_wants_chart(intent: ClarifyingUserIntent, user_query: str) -> bool:
    """Return True if the user explicitly requested a chart or visualization."""
    query_lower = user_query.lower()
    return any(kw in query_lower for kw in _CHART_KEYWORDS)
